spring:
  datasource:
    url: jdbc:mysql://localhost:3306/medvind?useLegacyDatetimeCode=false&characterEncoding=UTF-8&createDatabaseIfNotExist=true&serverTimezone=UTC
    platform: mysql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none #should be none in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


# OAuth2 client configuration
security:
  oauth2:
    resource:
      userInfoUri: BUGFIX
    client:
      clientId: ${CLIENT_ID}
        clientSecret: ${CLIENT_SECRET}
      accessTokenUri: https://www.strava.com/oauth/token
      userAuthorizationUri: https://www.strava.com/oauth/authorize?response_type=code;scope=read
      clientAuthenticationScheme: form

